apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      paths:
      - /var/log/containers/*.log
      document_type: k8slog
      fields:
        document_type: k8slog
      tags: ["k8sapplog"]
      exclude_files:
      - filebeat.*log
      - kube.*log
      json.add_error_key: true
      json.keys_under_root: true
      json.message_key: log
      multiline.match: after
      multiline.pattern: ^\s
      symlinks: true
    logging.level: debug
    output.logstash:
      hosts: [ "logstash:5044" ]
      timeout: 15