apiVersion: v1
kind: ConfigMap
metadata:
  name: es-configmap
  namespace: elk
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME}
    node:
      name: ${NODE_NAME}
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      ingest: ${NODE_INGEST}
    network:
      host: ${NETWORK_HOST}
    path:
      data: /usr/share/elasticsearch/esdata/data
      logs: /usr/share/elasticsearch/esdata/log
    http:
      compression: true
      enabled: ${HTTP_ENABLE}
    discovery:
      zen:
        minimum_master_nodes: ${NUMBER_OF_MASTERS}
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
    xpack:
      graph.enabled: false
      ml.enabled: false
      monitoring.enabled: false
      security.enabled: false
      watcher.enabled: true
      notification.email.account:
        exchange_account:
          profile: outlook
          email_defaults:
            from: alerter@xxx.org
          smtp:
            auth: true
            starttls.enable: true
            host: smtp.exmail.qq.com
            user: alerter@xxx.org
            password: ******
    # thread_pool:
    #   index.size: 8
    #   search.size: 8
    #   bulk:
    #     size: 8
    #     queue_size: 1000
