apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-client
  namespace: elk
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 2
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      # Elasticsearch uses a hybrid mmapfs / niofs directory by default to
      # store its indices. The default operating system limits on mmap counts
      # is likely to be too low, which may result in out of memory exceptions,
      # so we use vm.max_map_count=262144 to increase that value.
      initContainers:
      - command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262144
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: "elastic/elasticsearch:6.5.1"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "256Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: elasticsearch-cluster
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: NETWORK_HOST
          value: _eth0_
        # The default value for this environment variable is 2, meaning a cluster
        # will need a minimum of 2 master nodes to operate. If you have 3 masters
        # and one dies, the cluster still works.
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: HTTP_ENABLE
          value: "true" 
        - name: NODE_DATA
          value: "false"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      # imagePullSecrets:
      # - name: {{ .Values.common.secretName }}
      volumes:
        - name: es-config
          configMap:
            name: es-configmap
        - emptyDir:
            medium: ""
          name: "storage"