apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: logstash-configmap
data:

  logstash.yml: |
    xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
    dead_letter_queue.enable: true
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: logstash_system
    xpack.monitoring.elasticsearch.password: Password1$

  logstash.conf: |
    input {
      beats {
        host => "0.0.0.0"
        port => 5043
      }
    }
    filter {
    }
    output {
      elasticsearch {
        hosts => [ "elasticsearch:9200" ]
        user => "elastic"
        password => "Password1$"
        manage_template => false
        index => "k8s-%{+YYYY.MM.dd}"
      }
    }

  # pipelines.yml: |
