apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-configmap
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    xpack.monitoring.enabled: false
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    xpack.reporting.enabled: false
    xpack.security.enabled: false
    xpack.canvas.enabled: false
    elasticsearch.url: http://elasticsearch:9200
    elasticsearch.username: kibana
    elasticsearch.password: Password1$