apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana
  labels:
    component: kibana
spec:
  type: ClusterIP
  selector:
    component: kibana
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5601