apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash
  labels:
    component: logstash
spec:
  type: ClusterIP
  selector:
    component: logstash
  ports:
  - name: http
    port: 5044
    protocol: TCP
    targetPort: 5044
  - name: api
    port: 9600
    protocol: TCP
    targetPort: 9600